### ISSUE TITLE
[Epic] dbt-semantic-interfaces 0.3.0

### ISSUE THREAD

**Issue by QMalcolm** [dbt-labs/dbt-semantic-interfaces#140]
```[tasklist]
# Features
- [ ] https://github.com/dbt-labs/dbt-semantic-interfaces/issues/142
- [ ] https://github.com/dbt-labs/dbt-semantic-interfaces/issues/143
- [ ] https://github.com/dbt-labs/dbt-semantic-interfaces/issues/144
```

```[tasklist]
# Nice to haves
- [ ] #135
- [ ] #134
- [ ] #118
- [ ] #104
```
