### ISSUE TITLE
[EPIC] 0.4.0

### ISSUE THREAD

**Issue by QMalcolm** [dbt-labs/dbt-semantic-interfaces#191]
```[tasklist]
### Tasks
- [ ] https://github.com/dbt-labs/dbt-semantic-interfaces/pull/186
- [ ] https://github.com/dbt-labs/dbt-semantic-interfaces/issues/181
- [ ] https://github.com/dbt-labs/dbt-semantic-interfaces/issues/180
- [ ] https://github.com/dbt-labs/dbt-semantic-interfaces/issues/188
- [ ] https://github.com/dbt-labs/dbt-semantic-interfaces/issues/189
- [ ] Release 0.4.0
```

**Comment by QMalcolm** [comment]
There's an open question on whether we're trying to get https://github.com/dbt-labs/dbt-semantic-interfaces/pull/187 in 0.4.0

**Comment by r-richmond** [comment]
Can we get https://github.com/dbt-labs/dbt-semantic-interfaces/issues/134 added?

**Comment by QMalcolm** [comment]
@r-richmond apologies that I didn't respond sooner to this. DSI 0.4.0 was kind of a mad dash for us to ensure compatibility between MetricFlow and dbt-core. #134 is something we want to do, but are trying to balance with the other things we need to get done and the bandwidth we have. We'd absolutely welcome contributions to get us moved over.
