### ISSUE TITLE
[Feature] Add meta tag to dimensions, entities and measures 

### ISSUE THREAD

**Issue by Jstein77** [dbt-labs/dbt-semantic-interfaces#195]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward change to existing dbt-semantic-interfaces functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Annotating entities/dimensions/metrics/measures is a pretty reasonable thing for people to want to do! The `meta` tag is a place for people to add custom metadata that we haven't formalized as part of the interface yet.

**Comment by ataft** [comment]
@nhandel @Jstein77 Any updates on getting `meta` onto models, dimensions, and measures in the semantic interfaces YAML? My customers are all stuck on dbt v1.5 (old metrics) until we can use the meta tag. 

Referencing Nov 9, 2023 discussion with Nick on this topic:
https://github.com/dbt-labs/dbt-core/discussions/7456#discussioncomment-7528393

I also see the following PR, but it appears to handle models and measures, not dimensions?
https://github.com/dbt-labs/dbt-semantic-interfaces/pull/250

**Comment by Jstein77** [comment]
Hey @ataft sorry for the long delay! I missed this notification. We're discussing this when to pick this task up now. I'll update the status here when we're actively working on it.
