### ISSUE TITLE
[SL-1325] [EPIC] DSI 0.5.0

### ISSUE THREAD

**Issue by QMalcolm** [dbt-labs/dbt-semantic-interfaces#223]
```[tasklist]
### Tasks
- [ ] https://github.com/dbt-labs/dbt-semantic-interfaces/issues/210
- [ ] https://github.com/dbt-labs/dbt-semantic-interfaces/issues/134
- [ ] https://github.com/dbt-labs/dbt-semantic-interfaces/issues/228
```

<sub>From [SyncLinear.com](https://synclinear.com) | [SL-1325](https://linear.app/dbt-labs/issue/SL-1325/[epic]-dsi-050)</sub>

**Comment by QMalcolm** [comment]
Hey linear sync, can you stop destroying task lists? 👀
