### ISSUE TITLE
[SL-1563] [Feature] Add `meta` to Metric/SemanticModel

### ISSUE THREAD

**Issue by WilliamDee** [dbt-labs/dbt-semantic-interfaces#251]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward change to existing dbt-semantic-interfaces functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

There has been requests to expose the `meta` field that's parsed by dbt-core to our interfaces. This would allow users to annotate freely with that field and have that be exposed on our SL APIs. However, this is only supported currently for Metric/SemanticModel, the other are addressed here [https://github.com/dbt-labs/dbt-semantic-interfaces/issues/195](https://github.com/dbt-labs/dbt-semantic-interfaces/issues/195)

#### Spec changes:

**SemanticModels**
No dbt-core changes needed as it already exists, just need to expose in DSI

```
semantic_models:
 - name: my_model
   config:
     meta
```

**Metrics**
Currently, `meta` exists on the top-level of Metric. @quigley.malcolm mentioned that it should be moved to be nested under `config`. Then we can make the necessary changes in DSI.

```
metrics:
 - name: my_metric
   meta: ...
```

to

```
metrics:
 - name: my_metric
   config:
     meta: ...
```

### Describe alternatives you've considered

*No response*

### Who will this benefit?

Any users interacting with the SL APIs who needs to annotate their metrics or semantic models via their own structure.

### Are you interested in contributing this feature?

*No response*

### Anything else?

*No response*

<sub>From [SyncLinear.com](https://synclinear.com) | [SL-1563](https://linear.app/dbt-labs/issue/SL-1563/[feature]-add-meta-to-metricsemanticmodel)</sub>

**Comment by Jstein77** [comment]
Metrics needs to nest meta under config.

**Comment by WilliamDee** [comment]
@jordan.stein this is merged btw!
