### ISSUE TITLE
[Feature] Support for meta in Dimensions, Entities, and Measures

### ISSUE THREAD

**Issue by DevonFulcher** [dbt-labs/dbt-semantic-interfaces#362]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward change to existing dbt-semantic-interfaces functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Dimensiona, Entities, and Measures should have meta config like other dbt resources https://docs.getdbt.com/reference/resource-configs/meta.

### Who will this benefit?

This will provide consistency across dbt resources.

### Are you interested in contributing this feature?

Yes.

### Anything else?

I have already started on this [here](https://github.com/dbt-labs/dbt-semantic-interfaces/pull/358). The biggest open question is how to implement combining configs, such as here https://docs.getdbt.com/reference/configs-and-properties#combining-configs. This behavior is a bit confusing to me and there may be a problem with our docs our a bug in the implementation. For example, In this case, there is no `meta_location_1` in the manifest:
```
sources:
  - name: source_1
    config:
      meta: {"meta_location": "source level1", "meta_location_1": "source level2"}

    tables:
      - name: table_1
        config:
          meta: {"meta_location": "table level3", "meta_location_2": "table level4"}
```
However, in this case there is:
```
sources:
  - name: source_1
    config:
      meta: {"meta_location": "source level1", "meta_location_1": "source level2"}

    tables:
      - name: table_1
```
So, it looks like these meta dictionaries aren't being merged as described in the docs.

**Comment by Jstein77** [comment]
@DevonFulcher I think we can move forward with the behavior described in the docs and open a core issue to fix the "clobbering" behaviour. How does that sound?
