### ISSUE TITLE
[CT-2353][Epic] Initial build out of new package `dbt-semantic-interfaces` for sharing of semantic layer interfaces

### ISSUE THREAD

**Issue by QMalcolm** [dbt-labs/dbt-semantic-interfaces#7]
As noted in https://github.com/dbt-labs/dbt-core/discussions/7456, for the integration of dbt-core and MetricFlow we are creating a third repo to put the shared semantic interface defintions. This is that repo. What that entails is protocol definitions for the semantic interfaces, default object implementations, default parsing / transformations / validations, and associated tests.

```[tasklist]
- [ ] https://github.com/dbt-labs/dbt-semantic-interfaces/issues/1
- [ ] https://github.com/dbt-labs/dbt-semantic-interfaces/issues/2
- [ ] https://github.com/dbt-labs/dbt-semantic-interfaces/issues/8
- [ ] https://github.com/dbt-labs/dbt-semantic-interfaces/issues/9
- [ ] https://github.com/dbt-labs/dbt-semantic-interfaces/issues/10
- [ ] https://github.com/dbt-labs/dbt-semantic-interfaces/issues/11
- [ ] https://github.com/dbt-labs/dbt-semantic-interfaces/issues/12
- [ ] https://github.com/dbt-labs/dbt-semantic-interfaces/issues/13
- [ ] https://github.com/dbt-labs/dbt-semantic-interfaces/issues/14
- [ ] https://github.com/dbt-labs/dbt-semantic-interfaces/issues/15
- [ ] https://github.com/dbt-labs/dbt-semantic-interfaces/issues/16
- [ ] https://github.com/dbt-labs/dbt-semantic-interfaces/issues/17
- [ ] https://github.com/dbt-labs/dbt-semantic-interfaces/issues/18
- [ ] https://github.com/dbt-labs/dbt-semantic-interfaces/issues/19
- [ ] https://github.com/dbt-labs/dbt-semantic-interfaces/issues/20
- [ ] https://github.com/dbt-labs/dbt-semantic-interfaces/issues/21
```

```[tasklist]
# Right Now Refactors
- [ ] https://github.com/dbt-labs/dbt-semantic-interfaces/issues/48
- [ ] https://github.com/dbt-labs/dbt-semantic-interfaces/issues/49
- [ ] https://github.com/dbt-labs/dbt-semantic-interfaces/issues/50
- [ ] https://github.com/dbt-labs/dbt-semantic-interfaces/issues/30
```

```[tasklist]
# Public Alpha Refactors
- [ ] https://github.com/dbt-labs/dbt-semantic-interfaces/issues/51
- [ ] https://github.com/dbt-labs/dbt-semantic-interfaces/issues/53
- [ ] https://github.com/dbt-labs/dbt-semantic-interfaces/issues/54
- [ ] https://github.com/dbt-labs/dbt-semantic-interfaces/issues/55
- [ ] https://github.com/dbt-labs/dbt-semantic-interfaces/issues/67
```

```[tasklist]
# Public Beta Refactors
- [ ] https://github.com/dbt-labs/dbt-semantic-interfaces/issues/56
- [ ] https://github.com/dbt-labs/dbt-semantic-interfaces/issues/57
```
